#############################################################################
# Makefile for building: SpriteSheet
# Generated by qmake (3.0) (Qt 5.1.1) on: Mon Jan 13 18:03:18 2014
# Project:  SpriteSheet.pro
# Template: app
# Command: /opt/Qt/5.1.1/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile SpriteSheet.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc -std=c99
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -I/usr/local/include/SDL2 -D_REENTRANT -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/Qt/5.1.1/gcc_64/mkspecs/linux-g++ -I. -I/opt/Qt/5.1.1/gcc_64/include -I/opt/Qt/5.1.1/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/Qt/5.1.1/gcc_64 -Wl,-rpath,/opt/Qt/5.1.1/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lSDL2 -lSDL2_image -L/opt/Qt/5.1.1/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/Qt/5.1.1/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = SpriteSheet.c 
OBJECTS       = SpriteSheet.o
DIST          = /opt/Qt/5.1.1/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/unix/default_pre.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/declarative_debug.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/wayland-scanner.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/lex.prf \
		SpriteSheet.pro \
		SpriteSheet.pro
QMAKE_TARGET  = SpriteSheet
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SpriteSheet


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: SpriteSheet.pro .qmake.cache /opt/Qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt/5.1.1/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/unix/default_pre.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/declarative_debug.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/wayland-scanner.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.1.1/gcc_64/mkspecs/features/lex.prf \
		SpriteSheet.pro \
		/opt/Qt/5.1.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile SpriteSheet.pro
/opt/Qt/5.1.1/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt/5.1.1/gcc_64/mkspecs/common/unix.conf:
/opt/Qt/5.1.1/gcc_64/mkspecs/common/linux.conf:
/opt/Qt/5.1.1/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt/5.1.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt/5.1.1/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt/5.1.1/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt/5.1.1/gcc_64/mkspecs/qconfig.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_v8.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/spec_post.prf:
.qmake.cache:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/unix/default_pre.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/qml_debug.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/declarative_debug.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/qt.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/resources.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/moc.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/wayland-scanner.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt/5.1.1/gcc_64/mkspecs/features/lex.prf:
SpriteSheet.pro:
/opt/Qt/5.1.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile SpriteSheet.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/SpriteSheet1.0.0 || mkdir -p .tmp/SpriteSheet1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SpriteSheet1.0.0/ && $(COPY_FILE) --parents SpriteSheet.c .tmp/SpriteSheet1.0.0/ && (cd `dirname .tmp/SpriteSheet1.0.0` && $(TAR) SpriteSheet1.0.0.tar SpriteSheet1.0.0 && $(COMPRESS) SpriteSheet1.0.0.tar) && $(MOVE) `dirname .tmp/SpriteSheet1.0.0`/SpriteSheet1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SpriteSheet1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland_server_header_make_all:
compiler_wayland_server_header_clean:
compiler_wayland_client_header_make_all:
compiler_wayland_client_header_clean:
compiler_qtwayland_client_header_make_all:
compiler_qtwayland_client_header_clean:
compiler_qtwayland_server_header_make_all:
compiler_qtwayland_server_header_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_wayland_code_make_all:
compiler_wayland_code_clean:
compiler_qtwayland_client_code_make_all:
compiler_qtwayland_client_code_clean:
compiler_qtwayland_server_code_make_all:
compiler_qtwayland_server_code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

SpriteSheet.o: SpriteSheet.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o SpriteSheet.o SpriteSheet.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

